# Generated by Django 3.1.12 on 2024-12-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trend1', models.CharField(blank=True, max_length=255, null=True)),
                ('trend2', models.CharField(blank=True, max_length=255, null=True)),
                ('trend3', models.CharField(blank=True, max_length=255, null=True)),
                ('trend4', models.CharField(blank=True, max_length=255, null=True)),
                ('trend5', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
